version: '3.8'
services:
  app:
    build: .
    image: rust-regex-gui:latest
    container_name: regex-gui
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
